name: fashow
description: Global app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  flutter_icons:
  curved_navigation_bar:
  font_awesome_flutter:
  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0+1
  firebase_storage: ^7.0.0
  firebase_analytics: ^7.0.1
  google_sign_in:
  image_picker:
  uuid:
  path_provider:
  animations:
  geolocator:
  cached_network_image:
  animator:
  timeago:
  firebase_messaging: ^6.0.16
  image:
  multi_image_picker:
  searchable_dropdown:
  flutter_multiselect:
  getwidget:
  eva_icons_flutter:
  flutter_image_compress:
  checkbox_formfield:
  community_material_icon:
  frino_icons:
  flutter_svg:
#  json_annotation: ^4.0.0
  provider:
  flutter_auth_buttons:
  number_inc_dec:
  carousel_slider:
  image_cropper:
  modal_progress_hud:
  inview_notifier_list:
#  quill_delta:
  flutter_markdown:
  permission_handler:
  emoji_picker:
  photo_view:
  fluttertoast:
  http:
  #  firebase_ml_vision: ^0.9.4
  rxdart:
  paginate_firestore:
#  dropdown_formfield:
  country_icons:
  transparent_image:
  smart_select:
  flutter_currencies_tracker:
  country_list_pick:
  get:
  contained_tab_bar_view:
  razorpay_flutter:
  smooth_star_rating:
#  zego_express_engine: ^2.2.0
  agora_rtc_engine: ^4.0.7
  agora_rtm: ^1.0.1
  sliding_up_panel:
  wakelock: any
  intl:
  gradient_text:
  flare_flutter:
  random_color:
  alert_dialog:
  badges:
  animated_text_kit:
  auto_size_text:
  buttons_tabbar:
  sizer:
  url_launcher:
  auto_search:
  bubble_tab_indicator:
  curved_splash_screen:
  splashscreen:
  custom_splash:
  animated_splash_screen:
  back_pressed:
  modal_bottom_sheet:
  flutter_chip_tags:
  flutter_country_picker:
  flutter_animated_button:
  neon:
  sticky_headers:
  firebase_dynamic_links:
  share: any
#  custom_timer:
#  firestore_collection:
#  zefyrka:
  bottom_bar:
  google_fonts:
#  video_player: ^2.2.10
#  insta_html_parser: ^0.1.1
#  ssinstafeedparser: ^0.0.1
#  neeko: ^0.0.10
#  ext_video_player: ^0.0.6
#  flutter_youtube_vimeo: ^0.0.1
#  youtube_player_flutter: ^7.0.0+1
  currency_formatter:
#  flutter_staggered_grid_view: ^0.4.1
#  video_player: any
#  fijkplayer: ^0.10.0
#  flick_video_player: any
  simple_polls:
  flutter_sticky_header:
#  simple_speed_dial: any
  lazy_loading_list:
  video_compress:
  cached_video_player: ^2.0.0-dev
  preload_page_view: ^0.1.6

  #  better_video_player:
#  better_player:
#  meta: ^1.7.0
  flutter_ffmpeg:
#  better_player: ^0.0.25
#  pigeon: ^1.0.7
#  textfield_tags: ^1.4.2


dependency_overrides:
  simple_speed_dial: ^4.6.6
#  video_player:
#    git:
#      url: git://github.com/syonip/plugins.git
#      ref: a669b59
#      path: packages/video_player

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/img/loading-38.gif
    - assets/img/loading-76.gif
    - assets/img/login_logo.png
    - assets/img/makeup.png
    - assets/img/man.svg
    - assets/img/F-PRIVATE-MODE.svg
    - assets/img/CAM.svg
    - assets/img/SEARCH.svg
    - assets/img/clap.png
    - assets/img/clap-hands.png
    - assets/img/babysizecloth.jpg
    - assets/img/kisclothsize.jpg
    - assets/img/MenClothingsize.jpg
    - assets/img/teenclothing.jpg
    - assets/img/WomanClothingsize.jpg
    - assets/img/cover.jpg
    - assets/img/design.png
    - assets/img/create content.png
    - assets/img/sell.png
    - assets/img/fashion show.png
    - assets/img/influence.png
    - assets/img/shop.png
    - assets/img/RING.jpg
    - assets/logos/fedex.png
    - assets/img/bohemian.jpg

  fonts:
    - family: AlteroDCU
      fonts:
        - asset: assets\fonts\Altero DCU\Altero-Outline.otf

    - family: AlteroDCURegular
      fonts:
        - asset: assets\fonts\Altero DCU\Altero-Regular.otf

    - family: Halfomania
      fonts:
        - asset: assets\fonts\Halfomania\Halfomania-Regular.ttf
    - family: Neoneon
      fonts:
        - asset: assets\fonts\Neoneon\Neoneon.otf
    - family: MajorMonoDisplay
      fonts:
        - asset: assets\fonts\MajorMonoDisplay\MajorMonoDisplay-Regular.ttf