import 'package:flutter/material.dart';
//import 'package:flutter_svg/svg.dart';
import 'package:flutter/cupertino.dart';
import 'package:intl/intl.dart';
String TaggerImg = "";
String TaggerId = "";
String TaggerName = "";
String TaggerCurrency = "";
String TaggerOwnerId = "";
String TaggerProdId = "";

Color kPrimaryColor = Colors.black;
 Color Cont = Colors.grey.shade200;
const Color appbar = Colors.black26;
const Color trans = Colors.transparent;
const Color transwhite = Colors.white38;
final oCcy = new NumberFormat("#,##0.00", "en_US");
var eurosInCurrentLocale = NumberFormat.currency(symbol: "€");
 bool tabs = false;
 bool duties = false;
String priceQuery = "0";
String AQuery = "A0";
String BQuery = "B0";
String CQuery = "C0";
String DQuery = "D0";
String EQuery = "E0";
String FQuery = "F0";
String GQuery = "G0";
String HQuery = "H0";
String IQuery = "I0";
String JQuery = "J0";
String KQuery = "K0";
String LQuery = "L0";
String MQuery = "M0";
String NQuery = "N0";
String OQuery = "O0";
String PQuery = "P0";
String QQuery = "Q0";
String RQuery = "R0";
String SQuery = "S0";
String desQuery = "des0";
String illQuery = "ill0";
String stylQuery = "styl0";
String blogQuery = "blog0";
String phoQuery = "pho0";
String modQuery = "mod0";
String makeQuery = "make0";
String hairQuery = "hair0";
String choQuery = "cho0";
String artQuery = "art0";
String fulfill = 'fulfill';
String accept = 'accept';
String full = 'full';
bool xxxs = false;
bool xxs = false;
bool xs = false;
bool s = false;
bool m = false;
bool l = false;
bool xl = false;
bool xxl = false;
bool xxxl = false;
bool fourl = false;
bool fivel = false;
bool sixl = false;
bool sevenl = false;
bool eightl = false;
bool ring1 = false;
bool ring2 = false;
bool ring3 = false;
bool ring4 = false;
bool ring5 = false;
bool ring6 = false;
bool ring7 = false;
bool ring8 = false;
bool ring9 = false;
bool ring10 = false;
bool ring11 = false;
bool ring12 = false;
bool ring13 = false;
bool ring14 = false;
bool ring15 = false;
bool ring16 = false;
bool ring17 = false;
bool ring18 = false;
bool ring19 = false;
bool ring20 = false;
bool ring21 = false;
bool ring22 = false;
bool ring23 = false;
bool shoe1 = false;
bool shoe2 = false;
bool shoe3 = false;
bool shoe4 = false;
bool shoe5 = false;
bool shoe6 = false;
bool shoe7 = false;
bool shoe8 = false;
bool shoe9 = false;
bool shoe10 = false;
bool shoe11 = false;
bool shoe12 = false;
bool shoe13 = false;
bool shoe14 = false;
bool shoe15 = false;
bool shoe16 = false;
bool shoe17 = false;
bool shoe18 = false;
bool shoe19 = false;
bool shoe20 = false;
bool shoe21 = false;
bool mtos = false;
bool frees = false;

bool  clothingIndex = false;
bool  shoesIndex = false;
bool  ringIndex = false;
String sizeFilter = "";
 final Gradient fabGradient = LinearGradient(
    colors: [ Color(0xff70e1f5),Color(0xffffd194)],
  begin: Alignment.topRight,
   end: Alignment.bottomLeft,
 );

const Color kSecondaryColor = Color(0xFFFFFFFF);
 Color kIcon = Colors.grey[400];
 Color kButton = Colors.pink.shade50;
const Color kSubtitle = Color(0xFFABB6B8);
const Color kUser = Color(0xFFAECCCC);
const Color kText = Colors.black;
const Color kGrey = Color(0xFF424242);
const Color kblue=Colors.indigoAccent;
const Color kTran=Colors.transparent;
const String MESSAGES_COLLECTION = "messages";
const String USERS_COLLECTION = "users";
const String CALL_COLLECTION = "call";
const String CONTACTS_COLLECTION = "contacts";

const String TIMESTAMP_FIELD = "timestamp";
const String EMAIL_FIELD = "email";

const String MESSAGE_TYPE_IMAGE = "image";


//const Color Ktransparentblue = Color(0XFF9B9BB4).withOpacity(0.3)
//const Color kBottomContainerColor = Color(0xFFEB1555);